### ISSUE TITLE
POST upload

### ISSUE THREAD

**Issue by skarphet** [mistergoodson/OCAP#14]
Any plans for supporting POST or PUT for uploading the JSON file? Makes things a lot easier for some people.

If you have no plans I'll see if I can't implement it and send a pull request.

**Comment by mistergoodson** [comment]
I have something planned that will make the JSON upload process easier.

**Comment by skarphet** [comment]
Great! Any ETA? I figure I can just make our own changes for now so we can start using it.

**Comment by mistergoodson** [comment]
Not sure on ETA.

Just to confirm, are you referring to uploading the JSON file from game-server to web-server (using POST)?

**Comment by skarphet** [comment]
Yeah, that's correct. Just as an attachment. I worked on it but had problems using HttpAsync, but I'll continue looking into it. Interested in me sending a pull request with it or should we just keep it in our own repository?

**Comment by mistergoodson** [comment]
Sorry, I just saw your reply. I managed to get this working, see #bec7380fc

**Comment by skarphet** [comment]
Awesome! We've used it for one operation so far and it's working really well (before bec7380)

Looking forward to the new release!

**Comment by mistergoodson** [comment]
Glad to hear it. By all means, feel free to create pull requests in the future :)
