### ISSUE TITLE
Admin Installed Map List not displaying installed maps correctly

### ISSUE THREAD

**Issue by simwah** [mistergoodson/OCAP#15]
Something is not going right with the latest maps added.

Maps are installed but not saying so in the console.

![capture](https://cloud.githubusercontent.com/assets/3753933/18567952/e5b904de-7bdd-11e6-85af-a0d00053cb8e.PNG)

maps.json

`[
	{
		"name": "Stratis",
		"worldName": "stratis",
		"worldSize": 8192,
		"imageSize": 16384,
		"multiplier": 2
	},
	{
		"name": "Isla Duala 3",
		"worldName": "isladuala3",
		"worldSize": 10240,
		"imageSize": 16384,
		"multiplier": 1.6
	},
	{
		"name": "Sara",
		"worldName": "sara",
		"worldSize": 20480,
		"imageSize": 16384,
		"multiplier": 0.8
	},
	{
		"name": "Reshmaan",
		"worldName": "reshmaan",
		"worldSize": 20480,
		"imageSize": 16384,
		"multiplier": 0.8
	},
	{
		"name": "Takistan",
		"worldName": "takistan",
		"worldSize": 12800,
		"imageSize": 16384,
		"multiplier": 1.28
	},
	{
		"name": "Tanoa",
		"worldName": "Tanoa",
		"worldSize": 15361,
		"imageSize": 16384,
		"multiplier": 1.06659723
	},
	{
		"name": "Clafghan",
		"worldName": "clafghan",
		"worldSize": 20491,
		"imageSize": 16384,
		"multiplier": 0.79957054
	},
	{
		"name": "Zargabad",
		"worldName": "Zargabad",
		"worldSize": 8193,
		"imageSize": 16384,
		"multiplier": 1.99975589
	},
	{
		"name": "Altis",
		"worldName": "Altis",
		"worldSize": 30721,
		"imageSize": 16384,
		"multiplier": 0.53331597
	},
	{
		"name": "Chernarus",
		"worldName": "Chernarus",
		"worldSize": 15361,
		"imageSize": 16384,
		"multiplier": 1.066597226743051
	},
	{
		"name": "Island Panthera",
		"worldName": "panthera3",
		"worldSize": 10240,
		"imageSize": 16384,
		"multiplier": 1.6
	},
	{
		"name": "Southern Sahrani",
		"worldName": "SaraLite",
		"worldSize": 10240,
		"imageSize": 16384,
		"multiplier": 1.6
	},
	{
		"name": "Everon",
		"worldName": "Eden",
		"worldSize": 12801,
		"imageSize": 16384,
		"multiplier": 1.2799
	},
	{
		"name": "Nogova",
		"worldName": "Noe",
		"worldSize": 12801,
		"imageSize": 16384,
		"multiplier": 1.2799
	},
	{
		"name": "Kolgujev",
		"worldName": "Cain",
		"worldSize": 12800,
		"imageSize": 16384,
		"multiplier": 1.28
	},
	{
		"name": "Rahmadi",
		"worldName": "Intro",
		"worldSize": 5121,
		"imageSize": 16384,
		"multiplier": 3.19937512205
	},
	{
		"name": "Utes",
		"worldName": "utes",
		"worldSize": 5120,
		"imageSize": 16384,
		"multiplier": 3.2
	},
	{
		"name": "Porto",
		"worldName": "Porto",
		"worldSize": 5121,
		"imageSize": 16384,
		"multiplier": 3.19937512205
	},
	{
		"name": "Shapur",
		"worldName": "Shapur_BAF",
		"worldSize": 2049,
		"imageSize": 16384,
		"multiplier": 7.99609565642
	},
	{
		"name": "Desert Island",
		"worldName": "Desert_Island",
		"worldSize": 12800,
		"imageSize": 16384,
		"multiplier": 1.28
	},
	{
		"name": "United Sahrani",
		"worldName": "Sara_DBE1",
		"worldSize": 20481,
		"imageSize": 16384,
		"multiplier": 0.7999609394
	}
]`

**Comment by mistergoodson** [comment]
This may sound strange, but can you replace any uppercase letters in your folder names with lowercase ones please? This may fix the issue.

**Comment by simwah** [comment]
@mistergoodson Yes that fixes it.

**Comment by mistergoodson** [comment]
Ok good. Folder names on the OCAP map repo have been renamed to lowercase only to correct this issue.
