### ISSUE TITLE
MariaDB Support

### ISSUE THREAD

**Issue by SchwererKonigstiger** [mistergoodson/OCAP#22]
Many webservers run on MariaDB over MySQL/SQLite, and this throws an error in the installer.
#1 is the root cause.

- [ ] Adding support for choosing between MariaDB/MySQL over SQLite
- [ ] Adding a check for SQLite/MariaDB as a prereq

However, since MariaDB and SQLite can be run at the same time, it isn't that _major_ an issue.
This should be something on the backburner unless you have free time.

**Comment by mistergoodson** [comment]
Useful feedback, thanks. As you said, this isn't a major issue at the moment, but it is something to be considered for future versions.

**Comment by mistergoodson** [comment]
Just to note - SQLite is server-less (meaning no need to run an SQL server/service), which makes it extremely easy to setup/run. Other than the user needing to install SQLite (#1), I'm not sure of any disadvantages.

**Comment by SchwererKonigstiger** [comment]
Aye. In that case, you may want to make
 - `sqlite3` 
 - `php5-sqsl` OR `php-sql` (depending on PHP version, I'm still on 7)
 - `libsqlite3-dev`
 into required packages I guess.

**Comment by mistergoodson** [comment]
Yep, good point. Will add this to next release.
