### ISSUE TITLE
Filter Functionality

### ISSUE THREAD

**Issue by simwah** [mistergoodson/OCAP#24]
The filter on the right hand side filters from the start of the text logs instead of anywhere in the recorded text logs.

Example:
Player Connected

If you try and filter for Connected it won't work.
If you filter for Player it will.

**Comment by mistergoodson** [comment]
Hmm, I can't seem to replicate this issue.
https://i.gyazo.com/d53b01b9ab3e8eb2e77023cbd4f15544.png

**Comment by simwah** [comment]
Gotta admit, now i cant either.
