### ISSUE TITLE
Loading Data Prompt

### ISSUE THREAD

**Issue by skarphet** [mistergoodson/OCAP#29]
Would be useful with a loading data prompt - we just had a 2 hour operation with 70~ players and the JSON takes a while to load. It just makes the screen go blank.

I'll try to send a pull request for this within a day or two. It may have been added already but I haven't seen it yet, at least.

**Comment by skarphet** [comment]
Looking at ocap.js, I found the following: https://github.com/mistergoodson/OCAP/blob/master/web/scripts/ocap.js#L872-L876

However, this modal never actually appears to be visible or it is the main modal and it simply disappears right after clicking, kind of defeating the point. Is this intended design?

**Comment by mistergoodson** [comment]
Good spot. The modal is supposed to display that message, then hide it after `processOp` is complete. However, since `processOp` is asynchronous, it hides the message almost immediately after showing it.
