### ISSUE TITLE
Error: "XXXoperation.json" could not be found

### ISSUE THREAD

**Issue by bux578** [mistergoodson/OCAP#30]
OCAP: Version 0.5.0.1 Beta
http://itsbux.com/ocap/

When trying to play back a 1h 40min operation the web part shows an error, that the json is file could not be found. (Note: Had to manually fix #18 and escape some of the strings)
![error](https://i.gyazo.com/0ef7b2ffb888823459eadfd9386f239a.png)

When looking at the web developer tools, one can see that the json file is actually trying to be loaded as an XHR request.
![xhr](https://i.gyazo.com/97dc9dad9356df4ae2118c590f63dbfb.png)

Though this request seems to fail after a few ms.

**Comment by bux578** [comment]
Used a small WinForms program to find the error in the json file (using Json.Net)

```c#
var path = "operation.json";
using (var streamReader = new StreamReader(path)) {
    using (var reader = new JsonTextReader(streamReader)) {
        var schema1 = JsonSchema.Read(reader);
    }
}
```

**Comment by Hawke442** [comment]
Care to share the program? Would like to check a json file i'm having a problem with.

**Comment by bux578** [comment]
@Hawke442 https://github.com/bux578/QuickJsonValidator/releases/tag/init

**Comment by Hawke442** [comment]
@bux578 Awesome! Cheers.
