### ISSUE TITLE
Make transmitting IP optional

### ISSUE THREAD

**Issue by DrLuke** [mistergoodson/OCAP#40]
On installation, the server ip is collected for statistical purposes. However not everyone might agree with having their IP collected.
This should be optional, as not everyone wants to do that.
And on top of that, you're also transmitting more information than just the ip address. For example you're also fetching the file root of the location where OCAP has been installed in. Why do you need to know this? It's a unnecessary privacy breach.

**Comment by mistergoodson** [comment]
Hello DrLuke. Yes I capture the server IP for stats (e.g. view count, capture count). I felt this would be useful for me to gauge OCAP usage. Also the folder name of where OCAP is located (i.e. /ocap) is recorded as it's useful for me to be able to watch back other's recordings (assuming they're available publicly of course).

I understand your concerns, however this is only the same (if not more private) as posting on your community forum (records IP/email/time last online/posts), or uploading a YouTube video (records view count/IP/email) etc.

**Comment by LennyPenny** [comment]
Yes but by visiting a website one actively agrees to them knowing your IP (otherwise you can't receive the answer to a http req for example), in this example you cannot know that you data is being sent out beforehand without reading the source code 

Just add a y/n prompt
