### ISSUE TITLE
User Marker Teleport - Wierd location

### ISSUE THREAD

**Issue by simwah** [mistergoodson/OCAP#42]
**OCAP Version:** `0.5.0.1`
**Server OS:** `Web: Ubuntu, DS: Windows`

**Description:** Wierd user location - Player Pegasus in Coop_Smash_Grab_Smash_v1-3 (http://riflingmatters.com/ocap/)

**Steps to reproduce:** Watch from minute 13 while following player, unit teleports then after a while teleports to the right position. (User does not have the ability to do this in the server)

**RPT File**

https://www.dropbox.com/s/9350keowm8vdodu/arma3server_2016-09-26_04-59-59.zip?dl=0

**Comment by JamieGoodson** [comment]
Closing since OCAP capture/playback logic has changed significantly since this issue was created. Will keep an eye out for this issue in future. Thanks.
