### ISSUE TITLE
Installation of map - locally

### ISSUE THREAD

**Issue by CptBananaPeel** [mistergoodson/OCAP#44]
**OCAP Version:** `0.5.0.1-beta`
**Server OS:** `Windows`

**Description:**
Whenever I try to load in a recording with a map, that is not in the current REPO, I get the errormessage "map is not installed" - which makes perfect sense. 
When i then add the map (zip, unzipped and added to the .json file) it still cannot load the map.
Is there any workaround for locally installation of maps?

**Steps to reproduce:**
1. record an opperation with a not supported map.
2. test playback-system for incompatibility
3. add correct map files to /image/maps including .json file
4. test playbacksystem. 

**RPT File**
N/A

**Comment by maxx87** [comment]
try this...
File: maps.json
go to your Mapname and set the same A3MapName in both vars:
"name": "Mapname",
"worldName": "Mapname",

for example:
{
	"name": "pja308",
	"worldName": "pja308",
	"worldSize": 20481,
	"imageSize": 16384,
	"multiplier": 0.79996
},

I fixed so my Problems... looks like a bug

**Comment by CptBananaPeel** [comment]
Sorry Maxx87, i haven't been able to obtain the same results. 
Still gives me an error about map-installation.

**Comment by maxx87** [comment]
yes, every time you have change something ... Strg + F5, and work...
