### ISSUE TITLE
Feature Request - Move recording compilation/finalization out of game

### ISSUE THREAD

**Issue by simwah** [mistergoodson/OCAP#5]
At the moment we have to end the mission with a command to "finalize" the recording.
This has some issues:
- If the command is not run, GG recording gone.
- The command can be run multiple times which can result in mutiple "operations" for the same mission

Idea:

Create a daemon that runs out of game that receives the recording data stream. Use this to build and compile the recording json file.

One step further to this could be streaming the data straight to the websever via an api.

This means if we #missions a mission instead of ending it can just finalize the recording.

This will also allow us to have "allways on" recording.

For some reference this is how the AAR recording from United Operations works. ( http://riflingmatters.com/aar/browse )

Happy to demo/talk about further.

**Comment by mistergoodson** [comment]
I have a possible solution that auto-exports capture at end of mission (including #missions). However, this does not involve streaming to the webserver. I like the idea of streaming, but I can't think of any reasons to do so if we can solve both your bullet points without the use of streaming. Other than being able to watch a stream live (as per #19), are there any other advantages that I haven't thought of?

**Comment by simwah** [comment]
- This would allow the removal of the ftp/transfer step to be removed. (Could be done with a post at the end too)
- Potentially allows for salvaging of missions when the dedicated server crashes
- Less storage on dedicated server (i know not a big thing lol)
- This obviously enables live streaming (#19) as highlighted.

**Comment by mistergoodson** [comment]
Point 1 is not really an issue. Transferring one large file, rather than lots of smaller data chunks, is more efficient.
Point 2 is a good point, but these are rare cases.

I can see the advantages of points 3 and 4 though, so this is perhaps something to aim for in future versions.

**Comment by JamieGoodson** [comment]
I've seen the light and eventually gone with this method (send a data stream rather than one large compilation at the end). This was partly due to the Arma 64-bit update which imposes a limit on in-game array size, forcing OCAP to have to flush capture data regularly.

Thanks for your suggestions, and sorry for the 2 year late response.
