### ISSUE TITLE
[QUESTION] Start recording Function

### ISSUE THREAD

**Issue by byjokese** [mistergoodson/OCAP#53]
Is there any function to make it start recording, from console? Same as stoping is doing.

**Comment by mistergoodson** [comment]
Yes, set `ocap_capture = false;` in your OCAP userconfig file. Then in debug console type `ocap_capture = true;`.

Note: Even if `ocap_capture == true`, capture will still not start unless number of players present is >= `ocap_minPlayerCount` (set in userconfig).

**Comment by byjokese** [comment]
Thank you. Great Work.

**Comment by byjokese** [comment]
Sorry, but having Web and Arma 3 server in different servers, is not yet implemented, right?
