### ISSUE TITLE
OCAP Export dont work with x64 Server

### ISSUE THREAD

**Issue by maxx87** [mistergoodson/OCAP#54]
**OCAP Version:** 0.5.0.1 Beta
**Arma 3 Version:** stable
**Server OS:** `Windows`

**Description:** 
OCAP Export dont work with x64 Server
Error: Call extension 'ocap_exporter' could not be found

**Steps to reproduce:**

1. Starting Arma 3 Server x64 with OCAP
2. Connect to Server x32 or x64
3. Capture with OCAP
4. Export Capture

**RPT File:**
http://pastebin.com/PdT5x47C

**Pull request:**
https://github.com/mistergoodson/OCAP/pull/55

**Fixed File:**
https://drive.google.com/file/d/0BzoKZYY0UB_VYzdSakpWYnRVV1k/view

**Comment by maxx87** [comment]
x64 compiled File to fix (Arma server's root folder):
https://drive.google.com/file/d/0BzoKZYY0UB_VYzdSakpWYnRVV1k/view

**Comment by ChristopheTdn** [comment]
in line 64 (https://github.com/mistergoodson/OCAP/blob/master/extension/OCAPExporter/OCAPExporter/Class1.cs#L64)
Change  "**_RVExtension@12**" reference  for 32-bit extension to "**RVExtension**"  for 64-bit "
and compile the dll in 64 environment

If you can t wait, use this one. ;-)

[ocap_exporter_x64.zip](https://github.com/mistergoodson/OCAP/files/892235/ocap_exporter_x64.zip)

**Comment by JamieGoodson** [comment]
An x64 release will be available soon (along with a much more efficient OCAP).
