### ISSUE TITLE
Ocap compatible with rented servers?

### ISSUE THREAD

**Issue by byjokese** [mistergoodson/OCAP#59]
Version 0.5.0.1 Beta

As FTP is not yet compatible. Sending Data to remote data base works, but i wonder if there is any chance of saving de data in local and sending the rest to remote we server. The idea is to do the FTP task manually.
The problem is that in a rented server I don't have access to full OS, so I cant get the absolute path for the json to be exported.

Is there any change of it working, we will have FTP capabilities on future as the config file says?

Thanks.

**Comment by byjokese** [comment]
Another question, Why FTP? If you record data in JSON why no to send it just through HTTP?

**Comment by MrDell61** [comment]
On the web there is a function to get json using http. You can try to use not the absolute path, but the relative one. For example: "Repeats /". Only the cabinet needs to be created separately. It is necessary to find out only as to what will be the path of the dll or Addons or Arma

**Comment by JamieGoodson** [comment]
The exported JSON is now saved locally, as well as sent to the OCAP webserver.

Added in commit https://github.com/mistergoodson/OCAP/commit/6941ffa8b2efa593056b96ef403853a29f194bd7
