### ISSUE TITLE
ErrorMessage: Too many virtual memory blocks requested

### ISSUE THREAD

**Issue by maxx87** [mistergoodson/OCAP#61]
**OCAP Version:** Version 0.5.0.1 Beta
**Server OS:** `Windows`

**Description:**
After ~2-2,5 h playtime server crashed

**Steps to reproduce:**
play with ocap more than ~2-3h

**RPT File**
[...]
2018/02/15, 21:31:22 OCAP: Captured frame 3660 (40.0391ms) :: Count(ocap_entitiesData): 510 :: Count(ocap_eventsData): 1713
...
2018/02/11, 21:50:17 OCAP: Captured frame 4190 (41.9922ms) :: Count(ocap_entitiesData): 408 :: Count(ocap_eventsData): 6537
...
2018/02/08, 22:07:08 OCAP: Captured frame 4470 (41.0156ms) :: Count(ocap_entitiesData): 425 :: Count(ocap_eventsData): 1355
...
2018/02/06, 22:19:13 OCAP: Captured frame 4630 (46.875ms) :: Count(ocap_entitiesData): 320 :: Count(ocap_eventsData): 153
...
2018/03/18, 21:58:42 OCAP: Captured frame 4470 (63.4766ms) :: Count(ocap_entitiesData): 598 :: Count(ocap_eventsData): 4558
...
2018/02/25, 21:12:38 OCAP: Captured frame 3130 (61.0352ms) :: Count(ocap_entitiesData): 497 :: Count(ocap_eventsData): 1597
...
ErrorMessage: Too many virtual memory blocks requested
[...]

**Comment by JamieGoodson** [comment]
The capture/export logic has recently been rewritten and this should no longer be an issue.
