### ISSUE TITLE
New version Release date

### ISSUE THREAD

**Issue by ehills** [mistergoodson/OCAP#66]
Hi there! Love your work!

Have been following daily for the last 6 months or so. I see work has died down however.
Any plans for this new re-write to be released soon? Alternatively are you open for others to help you finish it?

Cheers,
Ed

**Comment by JamieGoodson** [comment]
Hi Ed,

Sorry for being so slow with the update. With my job and busy weekends I find it very difficult to find the time and motivation to get this re-write finished. Every time I think I've finished it, more issues are found during testing (mostly performance and capture sync issues).

It's honestly very motivating hearing that you've been following this for the last 6 months. I don't want to set any dates or make any promises, but I will get this update out as soon as I'm happy with it. Sorry, I know that's probably not what you wanted to hear.

Thanks,
Jamie

**Comment by willithappen** [comment]
My community absolutely adores your work brother and would be ecstatic to see things continue, keep up the hard work
