### ISSUE TITLE
Stats server down

### ISSUE THREAD

**Issue by braingremlin85** [mistergoodson/OCAP#67]
**OCAP Version:** `0.5.0.1 beta`
**Server OS:** `Linux`

**Description:**
Stats server no more reachable so install fail

**Steps to reproduce:**
Try to install or just visit http://138.201.116.116

**RPT File**
Warning: file_get_contents(http://138.201.116.116/ocap/remote/ip.php): failed to open stream: Connection timed out in /var/www/html/ocap/install/install.php on line 16
Error: Failed adding this server to statistics database (invalid ID returned).
Install failed.

**Comment by JamieGoodson** [comment]
Thanks for reporting. A replacement will be available soon (once the OCAP rewrite is released).
