### ISSUE TITLE
CUP terrains support

### ISSUE THREAD

**Issue by Sniperhid** [mistergoodson/OCAP#9]
This ticket will serve as a progress tracker for CUP Terrains.

- [x] Chernarus
- [x] Chernarus Summer
- [x] Takistan
- [x] Zargabad
- [x] Utes
- [x] Proving Grounds
- [x] Bystrica
- [x] Takistan Mountains
- [x] Bukovina
- [x] Sahrani
- [x] United Sahrani
- [x] Southern Sahrani
- [x] Shapur
- [x] Rahmadi
- [x] Porto
- [x] Everon
- [x] Malden
- [x] Nogova
- [x] Kolgujev
- [x] Desert Island

**Comment by Sniperhid** [comment]
Southern Sahrani
N=1.6
Image Size=16384
Mapname, worldSize, displayName
["SaraLite",10240,"Southern Sahrani"]
http://1tac.tk/repo/ocap-islands/SaraLite.tar

Everon
N=1.2799
Mapname, worldSize, displayName
["Eden",12800,"Everon"]
http://1tac.tk/repo/ocap-islands/eden.tar

Nogova
N=1.2799
["Noe",12800,"Nogova"]
http://1tac.tk/repo/ocap-islands/noe.tar

Kolgujev
N=1.28
["Cain",12800,"Kolgujev"], 1.28
http://1tac.tk/repo/ocap-islands/cain.tar

**Comment by Sniperhid** [comment]
["Intro",12800,"Rahmadi"], N=3.19937512205
http://1tac.tk/repo/ocap-islands/Intro.tar

["utes",5120,"Utes"], N=3.2
http://1tac.tk/repo/ocap-islands/utes.tar

["Porto",5120,"Porto"], N=3.19937512205
http://1tac.tk/repo/ocap-islands/Porto.tar

["Shapur_BAF",2048,"Shapur"] N=7.99609565642
http://1tac.tk/repo/ocap-islands/Shapur_BAF.tar

**Comment by simwah** [comment]
@Sniperhid Make sure you map folders are in all lowercase. See #15

**Comment by Sniperhid** [comment]
Addressed in #34
